### ISSUE TITLE
refactor : 보안기능 개선

### ISSUE THREAD

**Issue by asklas** [prgrms-web-devcourse-final-project/WEB1_2_FlowDay_BE#25]
## 👀 개발 기능 설명
- jwt를 조금 더 안전하게 관리할 수 있도록 고안
-

## 🎙️ 기능 구현을 위한 계획
- 토큰 재발급과 관리에 대한 시도
-

## ⏰ 예상 작업 기간
-
-
-

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Implement a token reissuance mechanism and improve JWT security by adding token blacklisting, reducing token lifetime, and implementing refresh token rotation.

You can review changes in this commit: https://github.com/lkilu6456546/prgrms-web-devcourse-final-project-WEB1_2_FlowDay_BE-25/commit/d7970b06adbd620d1aa5083adc50281d7ae3c9cd.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
